# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "virtio_pci"
        "usbhid"
        "usb_storage"
        "sr_mod"
      ];
      kernelModules = [ ];
    };
    kernelModules = [ ];
    extraModulePackages = [ ];
  };
  
  fileSystems = {
    "/" = {
      device = "/dev/vda1";
      fsType = "ext4";
    };
    
    "/boot" = {
      device = "/dev/vda3";
      fsType = "vfat";
      # [2024-04-20] fix "⚠️ Mount point '/boot' which backs the random seed file is world accessible, which is a security hole! ⚠️" warning
      # https://github.com/NixOS/nixpkgs/issues/279362#issuecomment-1913506090
      # https://github.com/NixOS/nixpkgs/issues/279362#issuecomment-1883970541
      # https://discourse.nixos.org/t/security-warning-when-installing-nixos-23-11/37636/3      
      options = [
        "uid=0"
        "gid=0"
        "fmask=0077"
        "dmask=0077"
      ];
    };
  };

  swapDevices = [
    {
      device = "/dev/vda2";
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s1.useDHCP = lib.mkDefault true;
  
  # Set your system kind (needed for flakes)
  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}